language: node_js
node_js:
    - "8.9.4"
os: linux
#notifications:
#  slack:
#    rooms:
#      - xchips:YNUUwFmkbWCZWInBiHgwhsvU
#    on_success: change
cache:
    directories:
    - npm_modules
script: 
    - "npm install -g pxt"
    - "pxt target maker"
    - "pxt install"
    - "ls -lah pxt_modules"
    - "rm pxt_modules/test.ts"
    - "pxt build"
    - "rm -f -r pxt_modules"
    - "pxt target microbit"
    - "pxt install"
    - "pxt build"
    - "pxt test"
