notifications:
  slack:
    if: branch = master
    travis encrypt "xchips:YNUUwFmkbWCZWInBiHgwhsvU" --add notifications.slack
    on_success: change # default: always
    on_failure: always # default: always
#before_install:
#  - sudo apt-get -y install libusb-1.0-0-dev libudev-dev
language: node_js
node_js:
    - "8.9.4"
os: linux
cache:
    directories:
    - npm_modules
    - pxt_modules
jobs:
  include:
    #- stage: microbit
    #  script: 
    #    - "npm install -g pxt"
    #    - "pxt target microbit"
    #    - "pxt install"
    #    - "pxt build --cloud"

    - stage: maker
      script: 
        - "npm install -g pxt"
        - "pxt target maker"
        - "pxt install"
        - "pxt build --cloud"
